env = Environment()

env.Append(LIBS=["pninx","pniutils"])
env.Append(CXXFLAGS=["-O2","-std=c++0x"])
d4 = env.Program("d4.cpp")
nxfile_ex1 = env.Program("nxfile_ex1.cpp")
nxfile_ex2 = env.Program("nxfile_ex2.cpp")
nxgroup_ex1 = env.Program("nxgroup_ex1.cpp")
nxnumfield_ex1 = env.Program("nxnumfield_ex1.cpp")
nxnumfield_ex2 = env.Program("nxnumfield_ex2.cpp")
nxstrfield_ex1 = env.Program("nxstrfield_ex1.cpp")
nxstrfield_ex2 = env.Program("nxstrfield_ex2.cpp")
nxbinfield_ex1 = env.Program("nxbinfield_ex1.cpp")

