import os.path as path

Import("build_env")


#set here some directories
doxygen_doc_dir = "html"


doxygen_dict = {"@LIBPREFIX@":"${LIBPREFIX}","@LIBNAME@":"${LIBNAME}",
                "@VERSION@":"${VERSION}"}
doxygen_mainpage = build_env.Substfile(["mainpage.in"],SUBST_DICT=doxygen_dict)
doxyfile_source = ["Doxyfile.standard.in"]
doxyfile_source.extend(["Doxyfile.extension.in"])

doxyfile = build_env.Substfile(target="Doxyfile",source= doxyfile_source,
                               SUBST_DICT=doxygen_dict,SUBSTFILESUFFIX="")             

doxygen_doc = build_env.Command(["html"],doxyfile,
                                    "cd doc; doxygen $SOURCE.file")
build_env.Depends(doxygen_doc,[doxygen_mainpage])
build_env.Depends(doxygen_doc,Glob('../src/*.hpp'))
build_env.Depends(doxygen_doc,Glob('../src/h5/*.hpp'))

Clean(doxygen_doc,"html")


build_env.Alias("doc",[doxygen_doc])
doc_install = build_env.Install("${DOCDIR}","html")

build_env.Alias("all",[doxygen_doc])
build_env.Alias("install",[doc_install])


