import os.path as path

Import("build_env")


#set here some directories
api_doc_dir = "api-doc"
api_doc_html_dir = "html"


doxygen_dict = {"@LIBPREFIX@":"${LIBPREFIX}","@LIBNAME@":"${LIBNAME}",
                "@VERSION@":"${VERSION}"}
doxygen_mainpage = build_env.Substfile(["mainpage.in"],SUBST_DICT=doxygen_dict)
doxyfile_source = ["Doxyfile.standard.in"]
doxyfile_source.extend(["Doxyfile.extension.in"])

doxyfile = build_env.Substfile(target="Doxyfile",source= doxyfile_source,
                               SUBST_DICT=doxygen_dict,SUBSTFILESUFFIX="")             
            
doxygen_api_doc = build_env.Command(["api-doc/html"],doxyfile,
                                    "cd doc; doxygen $SOURCE.file")
build_env.Depends(doxygen_api_doc,[doxygen_mainpage])
build_env.Depends(doxygen_api_doc,Glob('../src/*.hpp'))
build_env.Depends(doxygen_api_doc,Glob('../src/h5/*.hpp'))

Clean(doxygen_api_doc,"api-doc")
admin_guide = SConscript("admin-guide/SConscript")
users_guide = SConscript("users-guide/SConscript")



build_env.Alias("doc",[doxygen_api_doc])
     
api_html_doc_install = build_env.Install("${DOCDIR}/api","api-doc/html")
admin_guide_install = build_env.Install("${DOCDIR}",admin_guide)
users_guide_install = build_env.Install("${DOCDIR}",users_guide)

build_env.Alias("pdfdoc",[admin_guide,users_guide])
build_env.Alias("pdfdocinstall",[admin_guide_install,users_guide_install])
build_env.Alias("all",[doxygen_api_doc])
build_env.Alias("install",[api_html_doc_install])


