Import("build_env")

from smod import DebChangelogFile

debian_dict = {"@SOURCE@":"$LIBPREFIX$LIBNAME","@MAINTAINER@":"$MAINTAINER",
               "@MAINTAINER_MAIL@":"$MAINTAINER_MAIL",
               "@PKGNAME@":"$PKGNAME","@VERSION@":"$VERSION",
               "@LIBINSTPATH@":"$LIBINSTPATH","@INCINSTPATH@":"$INCINSTPATH",
               "@DOCDIR@":"$DOCDIR"}
               
#-------------------------create control file-----------------------------------
                  
control_file = build_env.Substfile(["control.in"],SUBST_DICT=debian_dict)
build_env.Clean(control_file,"tmp")
build_env.Clean(control_file,Glob("*.log"))
build_env.Clean(control_file,Glob("*.substvars"))
build_env.Clean(control_file,Glob("*.debhelper"))
build_env.Clean(control_file,"${PKGNAME}")
build_env.Clean(control_file,"${PKGNAME}-dev")
build_env.Clean(control_file,"${PKGNAME}-doc")


changelog = DebChangelogFile("../","v0.0.1")
changelog.version=build_env["VERSION"]
changelog.pkg_name = build_env["LIBPREFIX"]+build_env["LIBNAME"]
changelog.urgency = "low"
changelog.distribution = "testing"
changelog.create("changelog.in")
changelog_file = build_env.Substfile(["changelog.in"])                                  

rules_file = build_env.Substfile(["rules.in"])

compat_file = build_env.Substfile(["compat.in"])

lib_pkg_dirs = build_env.Substfile(target="${PKGNAME}",
                source=["libpninx.dirs.in"],SUBST_DICT=debian_dict,
                SUBSTFILESUFFIX=".dirs")

lib_pkg_install = build_env.Substfile(target="${PKGNAME}",
                  source=["libpninx.install.in"],SUBST_DICT=debian_dict,
                  SUBSTFILESUFFIX=".install")

dev_pkg_dirs = build_env.Substfile(target="${PKGNAME}-dev",
               source = ["libpninx-dev.dirs.in"],
               SUBST_DICT=debian_dict,SUBSTFILESUFFIX=".dirs")

dev_pkg_install = build_env.Substfile(target="${PKGNAME}-dev",
                  source=["libpninx-dev.install.in"],SUBST_DICT=debian_dict,
                  SUBSTFILESUFFIX=".install")

doc_pkg_dirs = build_env.Substfile(target="${PKGNAME}-doc",
                                  source=["libpninx-doc.dirs.in"],
                                  SUBST_DICT=debian_dict,SUBSTFILESUFFIX=".dirs")

doc_pkg_install = build_env.Substfile(target="${PKGNAME}-doc",
                                     source=["libpninx-doc.install.in"],
                                     SUBST_DICT=debian_dict,
                                     SUBSTFILESUFFIX=".install")

debian = build_env.Alias("debian",[control_file,compat_file,lib_pkg_dirs,lib_pkg_install,
                          dev_pkg_dirs,dev_pkg_install,
                          doc_pkg_dirs,doc_pkg_install,changelog_file,rules_file])