var hierarchy =
[
    [ "pni::add_op< OP1T, OP2T >", "classpni_1_1add__op.html", null ],
    [ "pni::and_t< T1, T2 >", "structpni_1_1and__t.html", null ],
    [ "pni::array", "classpni_1_1array.html", null ],
    [ "pni::array_factory< ATYPE >", "structpni_1_1array__factory.html", null ],
    [ "pni::array_holder_interface", "classpni_1_1array__holder__interface.html", [
      [ "pni::array_holder< OT >", "classpni_1_1array__holder.html", null ]
    ] ],
    [ "pni::array_iterator< const_flag >", "classpni_1_1array__iterator.html", null ],
    [ "pni::array_iterator_types< const_flag >", "structpni_1_1array__iterator__types.html", null ],
    [ "pni::array_iterator_types< 0 >", "structpni_1_1array__iterator__types_3_010_01_4.html", null ],
    [ "pni::array_iterator_types< 1 >", "structpni_1_1array__iterator__types_3_011_01_4.html", null ],
    [ "pni::array_selection", "classpni_1_1array__selection.html", null ],
    [ "pni::array_trait< OP1, OPT2 >", "structpni_1_1array__trait.html", null ],
    [ "pni::array_trait< OP1, scalar< T > >", "structpni_1_1array__trait_3_01OP1_00_01scalar_3_01T_01_4_01_4.html", null ],
    [ "pni::array_trait< scalar< T >, OP1 >", "structpni_1_1array__trait_3_01scalar_3_01T_01_4_00_01OP1_01_4.html", null ],
    [ "pni::array_view< ATYPE >", "classpni_1_1array__view.html", null ],
    [ "pni::array_view_trait< ATYPE, is_view >", "structpni_1_1array__view__trait.html", null ],
    [ "pni::array_view_trait< ATYPE, false >", "structpni_1_1array__view__trait_3_01ATYPE_00_01false_01_4.html", null ],
    [ "pni::array_view_trait< ATYPE, true >", "structpni_1_1array__view__trait_3_01ATYPE_00_01true_01_4.html", null ],
    [ "pni::nexus::BaseClassFactory", "classpni_1_1nexus_1_1BaseClassFactory.html", null ],
    [ "pni::binary_t< NTYPE >", "classpni_1_1binary__t.html", null ],
    [ "pni::bool_t", "classpni_1_1bool__t.html", null ],
    [ "pni::nexus::xml::BuilderFactory", "classpni_1_1nexus_1_1xml_1_1BuilderFactory.html", null ],
    [ "pni::c_index_map_imp", "classpni_1_1c__index__map__imp.html", null ],
    [ "pni::checked_convertible< ST, TT >", "structpni_1_1checked__convertible.html", null ],
    [ "pni::column_info", "classpni_1_1column__info.html", null ],
    [ "pni::container_io_config", "classpni_1_1container__io__config.html", null ],
    [ "pni::container_iterator< ITERABLE >", "classpni_1_1container__iterator.html", null ],
    [ "pni::container_trait< CTYPE >", "structpni_1_1container__trait.html", null ],
    [ "pni::container_trait< array_view< ATYPE > >", "structpni_1_1container__trait_3_01array__view_3_01ATYPE_01_4_01_4.html", null ],
    [ "pni::container_trait< mdarray< STORAGE, IMAP, IPA > >", "structpni_1_1container__trait_3_01mdarray_3_01STORAGE_00_01IMAP_00_01IPA_01_4_01_4.html", null ],
    [ "pni::container_trait< std::array< T, N > >", "structpni_1_1container__trait_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", null ],
    [ "pni::container_trait< std::list< ARGS... > >", "structpni_1_1container__trait_3_01std_1_1list_3_01ARGS_8_8_8_01_4_01_4.html", null ],
    [ "pni::container_trait< std::vector< ARGS... > >", "structpni_1_1container__trait_3_01std_1_1vector_3_01ARGS_8_8_8_01_4_01_4.html", null ],
    [ "pni::container_utils< CTYPE >", "structpni_1_1container__utils.html", null ],
    [ "pni::container_utils< std::array< T, N > >", "structpni_1_1container__utils_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", null ],
    [ "pni::conversion_strategy< T, S, unchecked_convertible >", "structpni_1_1conversion__strategy.html", null ],
    [ "pni::conversion_strategy< hdf5::datatype::EBool, bool_t, true >", "structpni_1_1conversion__strategy_3_01hdf5_1_1datatype_1_1EBool_00_01bool__t_00_01true_01_4.html", null ],
    [ "pni::conversion_strategy< T, S, false >", "structpni_1_1conversion__strategy_3_01T_00_01S_00_01false_01_4.html", null ],
    [ "pni::conversion_trait< T >", "structpni_1_1conversion__trait.html", null ],
    [ "pni::conversion_trait< pni::int8 >", "structpni_1_1conversion__trait_3_01pni_1_1int8_01_4.html", null ],
    [ "pni::conversion_trait< pni::uint8 >", "structpni_1_1conversion__trait_3_01pni_1_1uint8_01_4.html", null ],
    [ "pni::converter< TT, ST >", "structpni_1_1converter.html", null ],
    [ "pni::converter< std::complex< BT >, ST >", "structpni_1_1converter_3_01std_1_1complex_3_01BT_01_4_00_01ST_01_4.html", null ],
    [ "pni::converter< std::complex< BTT >, std::complex< BST > >", "structpni_1_1converter_3_01std_1_1complex_3_01BTT_01_4_00_01std_1_1complex_3_01BST_01_4_01_4.html", null ],
    [ "pni::converter< TT, TT >", "structpni_1_1converter_3_01TT_00_01TT_01_4.html", null ],
    [ "pni::convertible< ST, TT >", "structpni_1_1convertible.html", null ],
    [ "pni::data_reader", "classpni_1_1data__reader.html", [
      [ "pni::image_reader", "classpni_1_1image__reader.html", [
        [ "pni::cbf_reader", "classpni_1_1cbf__reader.html", null ],
        [ "pni::tiff_reader", "classpni_1_1tiff__reader.html", null ]
      ] ],
      [ "pni::spreadsheet_reader", "classpni_1_1spreadsheet__reader.html", [
        [ "pni::fio_reader", "classpni_1_1fio__reader.html", null ]
      ] ]
    ] ],
    [ "pni::nexus::xml::DatasetCreationListBuilder", "classpni_1_1nexus_1_1xml_1_1DatasetCreationListBuilder.html", null ],
    [ "pni::nexus::xml::DataspaceBuilder", "classpni_1_1nexus_1_1xml_1_1DataspaceBuilder.html", null ],
    [ "pni::nexus::xml::DatatypeBuilder", "classpni_1_1nexus_1_1xml_1_1DatatypeBuilder.html", null ],
    [ "pni::nexus::DatatypeFactory", "classpni_1_1nexus_1_1DatatypeFactory.html", null ],
    [ "pni::nexus::xml::DataWriter", "classpni_1_1nexus_1_1xml_1_1DataWriter.html", null ],
    [ "pni::nexus::DateTime", "classpni_1_1nexus_1_1DateTime.html", null ],
    [ "pni::cbf::dectris_reader", "classpni_1_1cbf_1_1dectris__reader.html", null ],
    [ "pni::nexus::xml::DimensionNodeHandler", "classpni_1_1nexus_1_1xml_1_1DimensionNodeHandler.html", null ],
    [ "pni::div_op< OP1T, OP2T >", "classpni_1_1div__op.html", null ],
    [ "std::exception", null, [
      [ "pni::exception", "classpni_1_1exception.html", [
        [ "pni::cli_argument_error", "classpni_1_1cli__argument__error.html", null ],
        [ "pni::cli_error", "classpni_1_1cli__error.html", null ],
        [ "pni::cli_help_request", "classpni_1_1cli__help__request.html", null ],
        [ "pni::cli_option_error", "classpni_1_1cli__option__error.html", null ],
        [ "pni::file_error", "classpni_1_1file__error.html", null ],
        [ "pni::index_error", "classpni_1_1index__error.html", null ],
        [ "pni::invalid_object_error", "classpni_1_1invalid__object__error.html", null ],
        [ "pni::io_error", "classpni_1_1io__error.html", null ],
        [ "pni::iterator_error", "classpni_1_1iterator__error.html", null ],
        [ "pni::key_error", "classpni_1_1key__error.html", null ],
        [ "pni::link_error", "classpni_1_1link__error.html", null ],
        [ "pni::memory_allocation_error", "classpni_1_1memory__allocation__error.html", null ],
        [ "pni::memory_not_allocated_error", "classpni_1_1memory__not__allocated__error.html", null ],
        [ "pni::not_implemented_error", "classpni_1_1not__implemented__error.html", null ],
        [ "pni::object_error", "classpni_1_1object__error.html", null ],
        [ "pni::parser_error", "classpni_1_1parser__error.html", null ],
        [ "pni::range_error", "classpni_1_1range__error.html", null ],
        [ "pni::shape_mismatch_error", "classpni_1_1shape__mismatch__error.html", null ],
        [ "pni::size_mismatch_error", "classpni_1_1size__mismatch__error.html", null ],
        [ "pni::tiff::tiff_read_error", "classpni_1_1tiff_1_1tiff__read__error.html", null ],
        [ "pni::type_error", "classpni_1_1type__error.html", null ],
        [ "pni::value_error", "classpni_1_1value__error.html", null ]
      ] ]
    ] ],
    [ "pni::exception_record", "classpni_1_1exception__record.html", null ],
    [ "pni::nexus::FieldFactory", "classpni_1_1nexus_1_1FieldFactory.html", null ],
    [ "pni::format_config", "classpni_1_1format__config.html", null ],
    [ "pni::format_str< T >", "structpni_1_1format__str.html", null ],
    [ "pni::get_reference_type< T >", "structpni_1_1get__reference__type.html", null ],
    [ "pni::get_reference_type< std::reference_wrapper< T > >", "structpni_1_1get__reference__type_3_01std_1_1reference__wrapper_3_01T_01_4_01_4.html", null ],
    [ "pni::id_type_map< id >", "structpni_1_1id__type__map.html", null ],
    [ "pni::tiff::ifd", "classpni_1_1tiff_1_1ifd.html", null ],
    [ "pni::tiff::ifd_entry", "classpni_1_1tiff_1_1ifd__entry.html", null ],
    [ "pni::tiff::ifd_entry_reader< RTYPE, ETYPE >", "classpni_1_1tiff_1_1ifd__entry__reader.html", null ],
    [ "pni::tiff::ifd_entry_reader< pni::string, pni::string >", "classpni_1_1tiff_1_1ifd__entry__reader_3_01pni_1_1string_00_01pni_1_1string_01_4.html", null ],
    [ "pni::image_channel_info", "classpni_1_1image__channel__info.html", null ],
    [ "pni::image_info", "classpni_1_1image__info.html", null ],
    [ "pni::index_iterator< INDEXT, IMT >", "classpni_1_1index__iterator.html", null ],
    [ "pni::index_map< SHAPE_STORE, MAP_IMP >", "classpni_1_1index__map.html", null ],
    [ "pni::index_map< index_type, typename ATYPE::map_type::implementation_type >", "classpni_1_1index__map.html", null ],
    [ "pni::inplace_arithmetics", "structpni_1_1inplace__arithmetics.html", null ],
    [ "pni::is_array< T >", "structpni_1_1is__array.html", null ],
    [ "pni::is_complex_type< T >", "structpni_1_1is__complex__type.html", null ],
    [ "pni::is_float_type< T >", "structpni_1_1is__float__type.html", null ],
    [ "pni::is_index_type< T >", "structpni_1_1is__index__type.html", null ],
    [ "pni::is_index_types< ITYPES >::is_index_type_pred< T >", "structpni_1_1is__index__types_1_1is__index__type__pred.html", null ],
    [ "pni::is_index_types< ITYPES >", "structpni_1_1is__index__types.html", null ],
    [ "pni::is_integer_type< T >", "structpni_1_1is__integer__type.html", null ],
    [ "pni::is_non_numeric_type< T >", "structpni_1_1is__non__numeric__type.html", null ],
    [ "pni::is_numeric_type< T >", "structpni_1_1is__numeric__type.html", null ],
    [ "pni::is_primitive_type< T >", "structpni_1_1is__primitive__type.html", null ],
    [ "pni::is_reference_holder< T >", "structpni_1_1is__reference__holder.html", null ],
    [ "pni::is_reference_holder< std::reference_wrapper< T > >", "structpni_1_1is__reference__holder_3_01std_1_1reference__wrapper_3_01T_01_4_01_4.html", null ],
    [ "pni::is_valid_index< ITYPES >", "structpni_1_1is__valid__index.html", null ],
    [ "pni::is_view_cont< CTYPE >", "structpni_1_1is__view__cont.html", null ],
    [ "pni::is_view_cont< std::array< T, N > >", "structpni_1_1is__view__cont_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", null ],
    [ "pni::is_view_cont< std::vector< T > >", "structpni_1_1is__view__cont_3_01std_1_1vector_3_01T_01_4_01_4.html", null ],
    [ "pni::is_view_index< ITYPES >", "structpni_1_1is__view__index.html", null ],
    [ "pni::nexus::IsValidNeXusName", "classpni_1_1nexus_1_1IsValidNeXusName.html", null ],
    [ "pni::nx::xml::link", "classpni_1_1nx_1_1xml_1_1link.html", null ],
    [ "std::list< T >", null, [
      [ "pni::nexus::PathObjectList", "classpni_1_1nexus_1_1PathObjectList.html", null ]
    ] ],
    [ "pni::map_utils< MAPT >", "structpni_1_1map__utils.html", null ],
    [ "pni::map_utils< static_index_map< POLTYPE, DIMS... > >", "structpni_1_1map__utils_3_01static__index__map_3_01POLTYPE_00_01DIMS_8_8_8_01_4_01_4.html", null ],
    [ "pni::mdarray< STORAGE, IMAP, IPA >", "classpni_1_1mdarray.html", null ],
    [ "pni::min_max< T, is_float >", "structpni_1_1min__max.html", null ],
    [ "pni::min_max< T, true >", "structpni_1_1min__max_3_01T_00_01true_01_4.html", null ],
    [ "pni::mult_op< OP1T, OP2T >", "classpni_1_1mult__op.html", null ],
    [ "pni::nexus::NodePredicate", "classpni_1_1nexus_1_1NodePredicate.html", [
      [ "pni::nexus::IsBaseClass", "classpni_1_1nexus_1_1IsBaseClass.html", [
        [ "pni::nexus::IsData", "classpni_1_1nexus_1_1IsData.html", null ],
        [ "pni::nexus::IsDetector", "classpni_1_1nexus_1_1IsDetector.html", null ],
        [ "pni::nexus::IsEntry", "classpni_1_1nexus_1_1IsEntry.html", null ],
        [ "pni::nexus::IsInstrument", "classpni_1_1nexus_1_1IsInstrument.html", null ],
        [ "pni::nexus::IsSample", "classpni_1_1nexus_1_1IsSample.html", null ],
        [ "pni::nexus::IsSubentry", "classpni_1_1nexus_1_1IsSubentry.html", null ],
        [ "pni::nexus::IsTransformation", "classpni_1_1nexus_1_1IsTransformation.html", null ]
      ] ]
    ] ],
    [ "pni::none", "structpni_1_1none.html", null ],
    [ "pni::not_t< T >", "structpni_1_1not__t.html", null ],
    [ "pni::nexus::ObjectBuilder", "classpni_1_1nexus_1_1ObjectBuilder.html", [
      [ "pni::nexus::xml::ObjectBuilder", "classpni_1_1nexus_1_1xml_1_1ObjectBuilder.html", [
        [ "pni::nexus::xml::AttributeBuilder", "classpni_1_1nexus_1_1xml_1_1AttributeBuilder.html", null ],
        [ "pni::nexus::xml::FieldBuilder", "classpni_1_1nexus_1_1xml_1_1FieldBuilder.html", null ],
        [ "pni::nexus::xml::GroupBuilder", "classpni_1_1nexus_1_1xml_1_1GroupBuilder.html", null ],
        [ "pni::nexus::xml::LinkBuilder", "classpni_1_1nexus_1_1xml_1_1LinkBuilder.html", null ]
      ] ]
    ] ],
    [ "pni::op_trait< OT >", "structpni_1_1op__trait.html", null ],
    [ "pni::op_trait< OP1T >", "structpni_1_1op__trait.html", null ],
    [ "pni::op_trait< OP2T >", "structpni_1_1op__trait.html", null ],
    [ "pni::op_trait< scalar< T > >", "structpni_1_1op__trait_3_01scalar_3_01T_01_4_01_4.html", null ],
    [ "pni::or_t< T1, T2 >", "structpni_1_1or__t.html", null ],
    [ "pni::parser< T >", "classpni_1_1parser.html", null ],
    [ "pni::parser< base_type >", "classpni_1_1parser.html", null ],
    [ "pni::parser< hdf5::datatype::EBool >", "classpni_1_1parser_3_01hdf5_1_1datatype_1_1EBool_01_4.html", null ],
    [ "pni::parser< pni::bool_t >", "classpni_1_1parser_3_01pni_1_1bool__t_01_4.html", null ],
    [ "pni::parser< pni::complex64 >", "classpni_1_1parser.html", null ],
    [ "pni::parser< pni::float64 >", "classpni_1_1parser.html", null ],
    [ "pni::parser< pni::int64 >", "classpni_1_1parser.html", null ],
    [ "pni::parser< pni::slice >", "classpni_1_1parser_3_01pni_1_1slice_01_4.html", null ],
    [ "pni::parser< pni::string >", "classpni_1_1parser_3_01pni_1_1string_01_4.html", null ],
    [ "pni::parser< pni::value >", "classpni_1_1parser_3_01pni_1_1value_01_4.html", null ],
    [ "pni::parser< std::complex< T > >", "classpni_1_1parser_3_01std_1_1complex_3_01T_01_4_01_4.html", null ],
    [ "pni::parser< std::vector< T > >", "classpni_1_1parser_3_01std_1_1vector_3_01T_01_4_01_4.html", null ],
    [ "pni::parser< value_type >", "classpni_1_1parser.html", null ],
    [ "pni::nexus::Path", "classpni_1_1nexus_1_1Path.html", null ],
    [ "pni::nexus::PathObject", "classpni_1_1nexus_1_1PathObject.html", null ],
    [ "boost::property_tree::ptree", null, [
      [ "pni::nexus::xml::Node", "classpni_1_1nexus_1_1xml_1_1Node.html", null ]
    ] ],
    [ "pni::tiff::rational< T >", "classpni_1_1tiff_1_1rational.html", null ],
    [ "pni::scalar< T >", "classpni_1_1scalar.html", null ],
    [ "pni::scalar_iterator< ITERABLE >", "classpni_1_1scalar__iterator.html", null ],
    [ "pni::slice", "classpni_1_1slice.html", null ],
    [ "pni::static_index_map< MAP_IMP, DIMS >", "classpni_1_1static__index__map.html", null ],
    [ "pni::tiff::strip_reader", "classpni_1_1tiff_1_1strip__reader.html", null ],
    [ "pni::sub_op< OP1T, OP2T >", "classpni_1_1sub__op.html", null ],
    [ "pni::type_class_map< T >", "structpni_1_1type__class__map.html", null ],
    [ "pni::type_id_container_builder< CTYPE >", "classpni_1_1type__id__container__builder.html", null ],
    [ "pni::type_id_map< T >", "structpni_1_1type__id__map.html", null ],
    [ "pni::type_info< T >", "structpni_1_1type__info.html", null ],
    [ "hdf5::dataspace::TypeTrait< pni::array >", "classhdf5_1_1dataspace_1_1TypeTrait_3_01pni_1_1array_01_4.html", null ],
    [ "hdf5::datatype::TypeTrait< pni::array >", "classhdf5_1_1datatype_1_1TypeTrait_3_01pni_1_1array_01_4.html", null ],
    [ "hdf5::dataspace::TypeTrait< pni::mdarray< STORAGE, IMAP, IPA > >", "classhdf5_1_1dataspace_1_1TypeTrait_3_01pni_1_1mdarray_3_01STORAGE_00_01IMAP_00_01IPA_01_4_01_4.html", null ],
    [ "hdf5::datatype::TypeTrait< pni::mdarray< STORAGE, IMAP, IPA > >", "classhdf5_1_1datatype_1_1TypeTrait_3_01pni_1_1mdarray_3_01STORAGE_00_01IMAP_00_01IPA_01_4_01_4.html", null ],
    [ "pni::unchecked_convertible< ST, TT >", "structpni_1_1unchecked__convertible.html", null ],
    [ "pni::value", "classpni_1_1value.html", null ],
    [ "pni::value_converter< TT, ST, convertible >", "structpni_1_1value__converter.html", null ],
    [ "pni::value_converter< TT, ST, true >", "structpni_1_1value__converter_3_01TT_00_01ST_00_01true_01_4.html", null ],
    [ "pni::value_holder_interface", "classpni_1_1value__holder__interface.html", [
      [ "pni::value_holder< T >", "classpni_1_1value__holder.html", null ]
    ] ],
    [ "pni::value_ref", "classpni_1_1value__ref.html", null ],
    [ "hdf5::VarLengthStringTrait< pni::dynamic_array< std::string > >", "classhdf5_1_1VarLengthStringTrait_3_01pni_1_1dynamic__array_3_01std_1_1string_01_4_01_4.html", null ],
    [ "std::vector< T >", null, [
      [ "pni::nexus::AttributeList", "classpni_1_1nexus_1_1AttributeList.html", null ],
      [ "pni::nexus::DatasetList", "classpni_1_1nexus_1_1DatasetList.html", null ],
      [ "pni::nexus::GroupList", "classpni_1_1nexus_1_1GroupList.html", null ],
      [ "pni::nexus::NodeList", "classpni_1_1nexus_1_1NodeList.html", null ]
    ] ],
    [ "pni::nexus::Version", "classpni_1_1nexus_1_1Version.html", null ],
    [ "pni::view_provider< RTYPE, is_view >", "structpni_1_1view__provider.html", null ],
    [ "pni::view_provider< ATYPE, false >", "structpni_1_1view__provider_3_01ATYPE_00_01false_01_4.html", null ],
    [ "pni::view_provider< ATYPE, true >", "structpni_1_1view__provider_3_01ATYPE_00_01true_01_4.html", null ]
];